/** Flutter Knowledge Base */
export interface KnowledgeEntry { id: string; topic: string; category: string; summary: string; details: string[]; bestPractices: string[]; pitfalls: string[]; }
export const flutterKnowledge: KnowledgeEntry[] = [
  { id: "kb.flutter-sdk", topic: "Flutter SDK", category: "foundation", summary: "Flutter is Google's UI toolkit for building natively compiled apps from a single codebase.", details: ["Uses Dart language", "Compiles to native ARM", "Hot reload", "Widget-based UI"], bestPractices: ["Pin Flutter version", "Use flutter analyze in CI"], pitfalls: ["Not pinning SDK version", "Ignoring analyze warnings"] },
  { id: "kb.material-3", topic: "Material 3", category: "material", summary: "Latest Material Design with dynamic color and updated components.", details: ["ColorScheme.fromSeed()", "Updated components", "M3 typography"], bestPractices: ["Use ColorScheme.fromSeed()", "Set useMaterial3: true"], pitfalls: ["Hardcoding colors", "Mixing M2 and M3"] },
  { id: "kb.cupertino", topic: "Cupertino", category: "cupertino", summary: "iOS-style widgets following Apple's HIG.", details: ["CupertinoApp", "CupertinoNavigationBar"], bestPractices: ["Use Platform.isIOS to switch", "Provide Material fallbacks"], pitfalls: ["Using Cupertino on Android"] },
  { id: "kb.themes", topic: "Themes", category: "theme", summary: "Flutter theming with ThemeData, ColorScheme, TextTheme.", details: ["ThemeData.light/dark()", "ColorScheme.fromSeed()", "ThemeExtension"], bestPractices: ["Use ColorScheme.fromSeed()", "Theme.of(context)"], pitfalls: ["Hardcoding colors", "No dark mode"] },
  { id: "kb.navigation-gorouter", topic: "GoRouter", category: "navigation", summary: "Declarative routing with deep linking and redirects.", details: ["ShellRoute for bottom nav", "Auth redirects", "Type-safe navigation"], bestPractices: ["Use ShellRoute", "Implement auth redirects"], pitfalls: ["Imperative nav in declarative router"] },
  { id: "kb.slivers", topic: "Slivers", category: "scroll", summary: "Complex scrollable layouts with CustomScrollView.", details: ["SliverAppBar", "SliverList", "SliverGrid"], bestPractices: ["Use CustomScrollView for complex scroll"], pitfalls: ["Nesting scrollables"] },
];
export function getKnowledgeEntry(id: string): KnowledgeEntry | undefined { return flutterKnowledge.find(e => e.id === id); }
export function searchKnowledge(query: string): KnowledgeEntry[] { const q = query.toLowerCase(); return flutterKnowledge.filter(e => e.topic.toLowerCase().includes(q) || e.summary.toLowerCase().includes(q)); }
