/**
 * @module features/planner/registry
 *
 * Agent Registry — 17 placeholder agents. Each agent declares its
 * capabilities, allowed tools, and allowed models. Future phases implement
 * the actual agent logic; the registry + router are real today.
 */

import type { AgentDescriptor, AgentCategory } from "../types";

/** All 17 registered agents. */
export const agents: AgentDescriptor[] = [
  {
    id: "agent.planner",
    name: "Planner Agent",
    description: "Analyzes requests, creates goals, builds task graphs, and coordinates execution.",
    category: "planning",
    icon: "🧠",
    capabilities: ["intent-analysis", "goal-creation", "task-planning", "dependency-analysis", "strategy-selection"],
    allowedTools: ["search.find_file", "search.find_symbol", "search.find_text"],
    allowedModels: [],
    priority: "high",
    status: "idle",
    version: "0.1.0",
    health: "healthy",
    implemented: false,
  },
  {
    id: "agent.flutter",
    name: "Flutter Agent",
    description: "Generates and modifies Flutter widgets, screens, and app structures.",
    category: "flutter",
    icon: "🐦",
    capabilities: ["widget-generation", "screen-generation", "app-scaffolding", "flutter-best-practices"],
    allowedTools: ["fs.create_file", "fs.write_file", "fs.read_file", "search.find_widget"],
    allowedModels: [],
    priority: "high",
    status: "idle",
    version: "0.1.0",
    health: "healthy",
    implemented: false,
  },
  {
    id: "agent.ui",
    name: "UI Agent",
    description: "Designs and generates user interfaces with Material 3 and custom themes.",
    category: "ui",
    icon: "🎨",
    capabilities: ["ui-design", "theming", "layout", "animations", "responsive-design"],
    allowedTools: ["fs.create_file", "fs.write_file", "fs.read_file"],
    allowedModels: [],
    priority: "normal",
    status: "idle",
    version: "0.1.0",
    health: "healthy",
    implemented: false,
  },
  {
    id: "agent.riverpod",
    name: "Riverpod Agent",
    description: "Creates Riverpod providers, notifiers, and state management patterns.",
    category: "state",
    icon: "⚡",
    capabilities: ["provider-generation", "state-design", "riverpod-patterns", "consumer-widgets"],
    allowedTools: ["fs.create_file", "fs.write_file", "search.find_provider"],
    allowedModels: [],
    priority: "normal",
    status: "idle",
    version: "0.1.0",
    health: "healthy",
    implemented: false,
  },
  {
    id: "agent.supabase",
    name: "Supabase Agent",
    description: "Integrates Supabase Auth, Database, Storage, and Realtime.",
    category: "backend",
    icon: "🔥",
    capabilities: ["supabase-setup", "auth-integration", "database-queries", "realtime-sync"],
    allowedTools: ["fs.create_file", "fs.write_file"],
    allowedModels: [],
    priority: "normal",
    status: "idle",
    version: "0.1.0",
    health: "healthy",
    implemented: false,
  },
  {
    id: "agent.backend",
    name: "Backend Agent",
    description: "Builds backend services, repositories, and data layers.",
    category: "backend",
    icon: "🛠️",
    capabilities: ["service-generation", "repository-pattern", "data-layer", "api-client"],
    allowedTools: ["fs.create_file", "fs.write_file", "fs.read_file"],
    allowedModels: [],
    priority: "normal",
    status: "idle",
    version: "0.1.0",
    health: "healthy",
    implemented: false,
  },
  {
    id: "agent.api",
    name: "API Agent",
    description: "Designs and generates REST/GraphQL APIs and service classes.",
    category: "api",
    icon: "🔌",
    capabilities: ["api-design", "endpoint-generation", "request-models", "response-models"],
    allowedTools: ["fs.create_file", "fs.write_file"],
    allowedModels: [],
    priority: "normal",
    status: "idle",
    version: "0.1.0",
    health: "healthy",
    implemented: false,
  },
  {
    id: "agent.testing",
    name: "Testing Agent",
    description: "Writes unit, widget, and integration tests; runs coverage analysis.",
    category: "testing",
    icon: "🧪",
    capabilities: ["unit-tests", "widget-tests", "integration-tests", "mocking", "coverage"],
    allowedTools: ["fs.create_file", "fs.read_file", "flutter.test"],
    allowedModels: [],
    priority: "normal",
    status: "idle",
    version: "0.1.0",
    health: "healthy",
    implemented: false,
  },
  {
    id: "agent.debug",
    name: "Debug Agent",
    description: "Traces bugs, analyzes stack traces, and proposes fixes.",
    category: "debug",
    icon: "🐛",
    capabilities: ["bug-tracing", "stack-analysis", "root-cause", "fix-proposal"],
    allowedTools: ["search.find_text", "fs.read_file", "fs.write_file", "flutter.analyze"],
    allowedModels: [],
    priority: "high",
    status: "idle",
    version: "0.1.0",
    health: "healthy",
    implemented: false,
  },
  {
    id: "agent.review",
    name: "Review Agent",
    description: "Reviews code for quality, patterns, and best practices.",
    category: "review",
    icon: "👁️",
    capabilities: ["code-review", "quality-check", "pattern-analysis", "best-practices"],
    allowedTools: ["fs.read_file", "search.find_symbol"],
    allowedModels: [],
    priority: "normal",
    status: "idle",
    version: "0.1.0",
    health: "healthy",
    implemented: false,
  },
  {
    id: "agent.security",
    name: "Security Agent",
    description: "Audits code for vulnerabilities and security best practices.",
    category: "security",
    icon: "🔒",
    capabilities: ["security-audit", "vulnerability-scan", "input-validation", "auth-review"],
    allowedTools: ["fs.read_file", "search.find_text"],
    allowedModels: [],
    priority: "normal",
    status: "idle",
    version: "0.1.0",
    health: "healthy",
    implemented: false,
  },
  {
    id: "agent.performance",
    name: "Performance Agent",
    description: "Profiles and optimizes app performance.",
    category: "performance",
    icon: "🚀",
    capabilities: ["performance-profiling", "optimization", "memory-analysis", "rendering-analysis"],
    allowedTools: ["fs.read_file", "flutter.analyze"],
    allowedModels: [],
    priority: "normal",
    status: "idle",
    version: "0.1.0",
    health: "healthy",
    implemented: false,
  },
  {
    id: "agent.database",
    name: "Database Agent",
    description: "Designs schemas, creates migrations, and generates data models.",
    category: "database",
    icon: "🗄️",
    capabilities: ["schema-design", "migration-generation", "model-generation", "query-optimization"],
    allowedTools: ["fs.create_file", "fs.write_file"],
    allowedModels: [],
    priority: "normal",
    status: "idle",
    version: "0.1.0",
    health: "healthy",
    implemented: false,
  },
  {
    id: "agent.docs",
    name: "Documentation Agent",
    description: "Generates README, API docs, and inline comments.",
    category: "docs",
    icon: "📚",
    capabilities: ["documentation-generation", "readme-writing", "api-docs", "inline-comments"],
    allowedTools: ["fs.write_file", "fs.read_file", "search.find_symbol"],
    allowedModels: [],
    priority: "low",
    status: "idle",
    version: "0.1.0",
    health: "healthy",
    implemented: false,
  },
  {
    id: "agent.i18n",
    name: "Localization Agent",
    description: "Sets up internationalization and generates translations.",
    category: "i18n",
    icon: "🌍",
    capabilities: ["i18n-setup", "translation-generation", "locale-management"],
    allowedTools: ["fs.create_file", "fs.write_file"],
    allowedModels: [],
    priority: "low",
    status: "idle",
    version: "0.1.0",
    health: "healthy",
    implemented: false,
  },
  {
    id: "agent.git",
    name: "Git Agent",
    description: "Manages commits, branches, and pull requests.",
    category: "git",
    icon: "🌿",
    capabilities: ["commit-management", "branching", "pr-creation", "merge-resolution"],
    allowedTools: ["git.status", "git.commit", "git.branch", "git.checkout"],
    allowedModels: [],
    priority: "normal",
    status: "idle",
    version: "0.1.0",
    health: "healthy",
    implemented: false,
  },
  {
    id: "agent.deployment",
    name: "Deployment Agent",
    description: "Builds and deploys Flutter apps to stores and CI/CD.",
    category: "deployment",
    icon: "📦",
    capabilities: ["build-apk", "build-aab", "ci-cd-setup", "store-deployment"],
    allowedTools: ["flutter.build_apk", "flutter.build_aab", "flutter.clean"],
    allowedModels: [],
    priority: "high",
    status: "idle",
    version: "0.1.0",
    health: "healthy",
    implemented: false,
  },
];

/** Get an agent by id. */
export function getAgent(id: string): AgentDescriptor | undefined {
  return agents.find((a) => a.id === id);
}

/** List agents, optionally filtered by category. */
export function listAgents(category?: AgentCategory): AgentDescriptor[] {
  return category ? agents.filter((a) => a.category === category) : agents;
}

/** Count agents by status. */
export function agentStats(): {
  total: number;
  idle: number;
  busy: number;
  error: number;
  offline: number;
  healthy: number;
} {
  return {
    total: agents.length,
    idle: agents.filter((a) => a.status === "idle").length,
    busy: agents.filter((a) => a.status === "busy").length,
    error: agents.filter((a) => a.status === "error").length,
    offline: agents.filter((a) => a.status === "offline").length,
    healthy: agents.filter((a) => a.health === "healthy").length,
  };
}
