"use client";

import { create } from "zustand";
import type {
  ToolChain,
  SimulationResult,
  Recommendation,
  RecoveryPlan,
} from "@/features/tool-intelligence/types";
import type {
  ChainExecution,
  StepExecution,
} from "@/features/tool-intelligence/state/execution-types";
import type {
  ToolLearningSummary,
} from "@/features/tool-intelligence/types";
import { api } from "@/lib/api";
import type { IntentType } from "@/features/planner/types";

/**
 * Tool Intelligence Store — the top-level store for the Tool Intelligence
 * Layer. Holds the current chain, simulation, recommendations, recovery
 * plans, real-time execution state, and learning summaries.
 */
interface ToolIntelligenceState {
  chain: ToolChain | null;
  optimizedChain: ToolChain | null;
  simulation: SimulationResult | null;
  recommendations: Recommendation[];
  recoveryPlan: RecoveryPlan | null;
  /** AI-generated rationale for the current chain (empty if template-based). */
  rationale: string;
  /** Whether the current chain was generated by the AI builder. */
  aiGenerated: boolean;
  /** The most recent chain execution (real run against the Execution Engine). */
  execution: ChainExecution | null;
  /** All past executions (newest first). */
  executions: ChainExecution[];
  /** Per-tool learning summaries from real executions. */
  learningSummaries: ToolLearningSummary[];
  loading: boolean;
  executing: boolean;
  error: string | null;
  objective: string;
  intentType: IntentType;

  setObjective: (o: string) => void;
  setIntentType: (i: IntentType) => void;
  buildChain: (objective?: string, intentType?: IntentType) => Promise<void>;
  optimize: () => Promise<void>;
  simulate: () => Promise<void>;
  execute: () => Promise<void>;
  fetchExecutions: () => Promise<void>;
  fetchLearning: () => Promise<void>;
  clear: () => void;
}

export const useToolIntelligenceStore = create<ToolIntelligenceState>(
  (set, get) => ({
    chain: null,
    optimizedChain: null,
    simulation: null,
    recommendations: [],
    recoveryPlan: null,
    rationale: "",
    aiGenerated: false,
    execution: null,
    executions: [],
    learningSummaries: [],
    loading: false,
    executing: false,
    error: null,
    objective: "",
    intentType: "feature-request",

    setObjective: (objective) => set({ objective }),
    setIntentType: (intentType) => set({ intentType }),

    buildChain: async (objective, intentType) => {
      const obj = objective ?? get().objective;
      const intent = intentType ?? get().intentType;
      if (!obj.trim()) return;
      set({ loading: true, error: null });
      try {
        const response = await api.post<{
          data: {
            chain: ToolChain;
            recommendations: Recommendation[];
            rationale: string;
            aiGenerated: boolean;
          };
        }>("/tools/analyze", { objective: obj, intentType: intent });
        set({
          chain: response.data.chain,
          optimizedChain: null,
          simulation: null,
          execution: null,
          recommendations: response.data.recommendations ?? [],
          rationale: response.data.rationale ?? "",
          aiGenerated: response.data.aiGenerated ?? false,
          loading: false,
        });
      } catch (e: unknown) {
        set({
          loading: false,
          error: e instanceof Error ? e.message : "Analysis failed",
        });
      }
    },

    optimize: async () => {
      const { chain } = get();
      if (!chain) return;
      set({ loading: true, error: null });
      try {
        const response = await api.post<{ data: ToolChain }>(
          "/tools/optimize",
          { chainId: chain.id }
        );
        set({ optimizedChain: response.data, loading: false });
      } catch (e: unknown) {
        set({
          loading: false,
          error: e instanceof Error ? e.message : "Optimization failed",
        });
      }
    },

    simulate: async () => {
      const { chain } = get();
      if (!chain) return;
      set({ loading: true, error: null });
      try {
        const response = await api.post<{ data: SimulationResult }>(
          "/tools/simulate",
          { chainId: chain.id }
        );
        set({ simulation: response.data, loading: false });
      } catch (e: unknown) {
        set({
          loading: false,
          error: e instanceof Error ? e.message : "Simulation failed",
        });
      }
    },

    execute: async () => {
      const { chain } = get();
      if (!chain) return;
      set({ executing: true, error: null });
      try {
        const response = await api.post<{ data: ChainExecution }>(
          "/tools/execute",
          { chainId: chain.id, skipApproval: true, maxRetries: 2 }
        );
        const exec = response.data;
        set({
          execution: exec,
          executions: [exec, ...get().executions].slice(0, 50),
          executing: false,
        });
        // Refresh learning summaries after a real run.
        void get().fetchLearning();
      } catch (e: unknown) {
        set({
          executing: false,
          error: e instanceof Error ? e.message : "Execution failed",
        });
      }
    },

    fetchExecutions: async () => {
      try {
        const response = await api.get<{ data: ChainExecution[] }>(
          "/tools/execute"
        );
        set({ executions: response.data ?? [] });
      } catch {
        /* ignore */
      }
    },

    fetchLearning: async () => {
      try {
        const response = await api.get<{ data: ToolLearningSummary[] }>(
          "/tools/learn"
        );
        set({ learningSummaries: response.data ?? [] });
      } catch {
        /* ignore */
      }
    },

    clear: () =>
      set({
        chain: null,
        optimizedChain: null,
        simulation: null,
        execution: null,
        recommendations: [],
        recoveryPlan: null,
        rationale: "",
        aiGenerated: false,
        error: null,
      }),
  })
);

/** Helper: status colour for a step status. */
export function stepStatusColor(status: StepExecution["status"]): string {
  switch (status) {
    case "success":
      return "text-emerald-600 dark:text-emerald-400";
    case "failed":
      return "text-rose-600 dark:text-rose-400";
    case "skipped":
      return "text-muted-foreground";
    case "rolled-back":
      return "text-amber-600 dark:text-amber-400";
    case "running":
      return "text-sky-600 dark:text-sky-400";
    default:
      return "text-muted-foreground";
  }
}
