/**
 * @module features/flutter-platform/templates
 *
 * Real Flutter project templates — each template defines a set of files with
 * real Dart code that can be scaffolded into the virtual filesystem.
 */

import type { FlutterTemplate } from "../types";

/** A single file in a template. */
export interface TemplateFile {
  /** Relative path (e.g. "lib/main.dart"). */
  path: string;
  /** File content (Dart code or YAML). */
  content: string;
}

/** A complete template with files. */
export interface FlutterTemplateWithFiles extends FlutterTemplate {
  files: TemplateFile[];
}

/** All built-in templates. */
export const flutterTemplates: FlutterTemplateWithFiles[] = [
  {
    id: "tpl.counter-app",
    name: "Counter App",
    description: "Material 3 starter app with a counter and FAB.",
    category: "Starter",
    icon: "🔢",
    screens: ["HomeScreen"],
    widgets: ["Scaffold", "AppBar", "Center", "Column", "Text", "FloatingActionButton"],
    stateManagement: "setState",
    routing: "none",
    estimatedComplexity: "simple",
    generatesDart: true,
    files: [
      {
        path: "lib/main.dart",
        content: [
          "import 'package:flutter/material.dart';",
          "",
          "void main() => runApp(const CounterApp());",
          "",
          "class CounterApp extends StatelessWidget {",
          "  const CounterApp({super.key});",
          "",
          "  @override",
          "  Widget build(BuildContext context) {",
          "    return MaterialApp(",
          "      title: 'Counter',",
          "      theme: ThemeData(",
          "        colorScheme: ColorScheme.fromSeed(seedColor: Colors.teal),",
          "        useMaterial3: true,",
          "      ),",
          "      home: const HomeScreen(),",
          "    );",
          "  }",
          "}",
          "",
          "class HomeScreen extends StatefulWidget {",
          "  const HomeScreen({super.key});",
          "",
          "  @override",
          "  State<HomeScreen> createState() => _HomeScreenState();",
          "}",
          "",
          "class _HomeScreenState extends State<HomeScreen> {",
          "  int _count = 0;",
          "",
          "  void _increment() => setState(() => _count++);",
          "  void _decrement() => setState(() => _count--);",
          "",
          "  @override",
          "  Widget build(BuildContext context) {",
          "    return Scaffold(",
          "      appBar: AppBar(title: const Text('Counter')),",
          "      body: Center(",
          "        child: Column(",
          "          mainAxisAlignment: MainAxisAlignment.center,",
          "          children: [",
          "            const Text('You have pushed the button this many times:'),",
          "            Text('$_count', style: Theme.of(context).textTheme.displayMedium),",
          "          ],",
          "        ),",
          "      ),",
          "      floatingActionButton: Row(",
          "        mainAxisSize: MainAxisSize.min,",
          "        children: [",
          "          FloatingActionButton(heroTag: 'dec', onPressed: _decrement, child: const Icon(Icons.remove)),",
          "          const SizedBox(width: 8),",
          "          FloatingActionButton(heroTag: 'inc', onPressed: _increment, child: const Icon(Icons.add)),",
          "        ],",
          "      ),",
          "    );",
          "  }",
          "}",
          "",
        ].join("\n"),
      },
    ],
  },
  {
    id: "tpl.login-screen",
    name: "Login Screen",
    description: "Email + password login form with validation.",
    category: "Auth",
    icon: "🔐",
    screens: ["LoginScreen"],
    widgets: ["Scaffold", "TextField", "ElevatedButton", "Form"],
    stateManagement: "setState",
    routing: "none",
    estimatedComplexity: "simple",
    generatesDart: true,
    files: [
      {
        path: "lib/screens/login_screen.dart",
        content: [
          "import 'package:flutter/material.dart';",
          "",
          "class LoginScreen extends StatefulWidget {",
          "  const LoginScreen({super.key});",
          "",
          "  @override",
          "  State<LoginScreen> createState() => _LoginScreenState();",
          "}",
          "",
          "class _LoginScreenState extends State<LoginScreen> {",
          "  final _formKey = GlobalKey<FormState>();",
          "  final _emailController = TextEditingController();",
          "  final _passwordController = TextEditingController();",
          "  bool _obscure = true;",
          "",
          "  @override",
          "  void dispose() {",
          "    _emailController.dispose();",
          "    _passwordController.dispose();",
          "    super.dispose();",
          "  }",
          "",
          "  void _submit() {",
          "    if (_formKey.currentState?.validate() ?? false) {",
          "      // TODO: perform login",
          "      ScaffoldMessenger.of(context).showSnackBar(",
          "        const SnackBar(content: Text('Logging in...')),",
          "      );",
          "    }",
          "  }",
          "",
          "  @override",
          "  Widget build(BuildContext context) {",
          "    return Scaffold(",
          "      appBar: AppBar(title: const Text('Login')),",
          "      body: Padding(",
          "        padding: const EdgeInsets.all(24),",
          "        child: Form(",
          "          key: _formKey,",
          "          child: Column(",
          "            mainAxisAlignment: MainAxisAlignment.center,",
          "            children: [",
          "              Text('Welcome back',",
          "                  style: Theme.of(context).textTheme.headlineMedium),",
          "              const SizedBox(height: 24),",
          "              TextFormField(",
          "                controller: _emailController,",
          "                decoration: const InputDecoration(",
          "                  labelText: 'Email',",
          "                  border: OutlineInputBorder(),",
          "                  prefixIcon: Icon(Icons.email_outlined),",
          "                ),",
          "                keyboardType: TextInputType.emailAddress,",
          "                validator: (v) => (v == null || !v.contains('@'))",
          "                    ? 'Enter a valid email'",
          "                    : null,",
          "              ),",
          "              const SizedBox(height: 16),",
          "              TextFormField(",
          "                controller: _passwordController,",
          "                decoration: InputDecoration(",
          "                  labelText: 'Password',",
          "                  border: const OutlineInputBorder(),",
          "                  prefixIcon: const Icon(Icons.lock_outline),",
          "                  suffixIcon: IconButton(",
          "                    icon: Icon(_obscure ? Icons.visibility : Icons.visibility_off),",
          "                    onPressed: () => setState(() => _obscure = !_obscure),",
          "                  ),",
          "                ),",
          "                obscureText: _obscure,",
          "                validator: (v) =>",
          "                    (v == null || v.length < 6) ? 'Min 6 characters' : null,",
          "              ),",
          "              const SizedBox(height: 24),",
          "              SizedBox(",
          "                width: double.infinity,",
          "                child: ElevatedButton(",
          "                  onPressed: _submit,",
          "                  child: const Text('Login'),",
          "                ),",
          "              ),",
          "            ],",
          "          ),",
          "        ),",
          "      ),",
          "    );",
          "  }",
          "}",
          "",
        ].join("\n"),
      },
    ],
  },
  {
    id: "tpl.todo-app",
    name: "Todo App",
    description: "Add/remove/complete todos with persistence in memory.",
    category: "Productivity",
    icon: "✅",
    screens: ["TodoScreen"],
    widgets: ["ListView", "ListTile", "Checkbox", "TextField"],
    stateManagement: "setState",
    routing: "none",
    estimatedComplexity: "moderate",
    generatesDart: true,
    files: [
      {
        path: "lib/models/todo.dart",
        content: [
          "class Todo {",
          "  const Todo({required this.id, required this.title, this.done = false});",
          "",
          "  final String id;",
          "  final String title;",
          "  final bool done;",
          "",
          "  Todo copyWith({String? id, String? title, bool? done}) => Todo(",
          "        id: id ?? this.id,",
          "        title: title ?? this.title,",
          "        done: done ?? this.done,",
          "      );",
          "}",
          "",
        ].join("\n"),
      },
      {
        path: "lib/screens/todo_screen.dart",
        content: [
          "import 'package:flutter/material.dart';",
          "import '../models/todo.dart';",
          "",
          "class TodoScreen extends StatefulWidget {",
          "  const TodoScreen({super.key});",
          "",
          "  @override",
          "  State<TodoScreen> createState() => _TodoScreenState();",
          "}",
          "",
          "class _TodoScreenState extends State<TodoScreen> {",
          "  final _todos = <Todo>[];",
          "  final _controller = TextEditingController();",
          "",
          "  void _add() {",
          "    final title = _controller.text.trim();",
          "    if (title.isEmpty) return;",
          "    setState(() {",
          "      _todos.add(Todo(id: DateTime.now().toString(), title: title));",
          "      _controller.clear();",
          "    });",
          "  }",
          "",
          "  void _toggle(Todo todo) {",
          "    setState(() {",
          "      final i = _todos.indexOf(todo);",
          "      _todos[i] = todo.copyWith(done: !todo.done);",
          "    });",
          "  }",
          "",
          "  void _remove(Todo todo) {",
          "    setState(() => _todos.remove(todo));",
          "  }",
          "",
          "  @override",
          "  Widget build(BuildContext context) {",
          "    return Scaffold(",
          "      appBar: AppBar(title: const Text('Todos')),",
          "      body: Column(",
          "        children: [",
          "          Padding(",
          "            padding: const EdgeInsets.all(12),",
          "            child: Row(",
          "              children: [",
          "                Expanded(",
          "                  child: TextField(",
          "                    controller: _controller,",
          "                    decoration: const InputDecoration(",
          "                      hintText: 'Add a todo...',",
          "                      border: OutlineInputBorder(),",
          "                    ),",
          "                    onSubmitted: (_) => _add(),",
          "                  ),",
          "                ),",
          "                const SizedBox(width: 8),",
          "                IconButton.filled(",
          "                  icon: const Icon(Icons.add),",
          "                  onPressed: _add,",
          "                ),",
          "              ],",
          "            ),",
          "          ),",
          "          Expanded(",
          "            child: _todos.isEmpty",
          "                ? const Center(child: Text('No todos yet'))",
          "                : ListView.builder(",
          "                    itemCount: _todos.length,",
          "                    itemBuilder: (ctx, i) {",
          "                      final todo = _todos[i];",
          "                      return ListTile(",
          "                        leading: Checkbox(",
          "                          value: todo.done,",
          "                          onChanged: (_) => _toggle(todo),",
          "                        ),",
          "                        title: Text(",
          "                          todo.title,",
          "                          style: TextStyle(",
          "                            decoration: todo.done",
          "                                ? TextDecoration.lineThrough",
          "                                : TextDecoration.none,",
          "                          ),",
          "                        ),",
          "                        trailing: IconButton(",
          "                          icon: const Icon(Icons.delete_outline),",
          "                          onPressed: () => _remove(todo),",
          "                        ),",
          "                      );",
          "                    },",
          "                  ),",
          "          ),",
          "        ],",
          "      ),",
          "    );",
          "  }",
          "}",
          "",
        ].join("\n"),
      },
    ],
  },
  {
    id: "tpl.master-detail",
    name: "Master-Detail",
    description: "Responsive master-detail layout with route navigation.",
    category: "Navigation",
    icon: "📑",
    screens: ["MasterScreen", "DetailScreen"],
    widgets: ["ListView", "Navigator", "Hero"],
    stateManagement: "setState",
    routing: "Navigator",
    estimatedComplexity: "moderate",
    generatesDart: true,
    files: [
      {
        path: "lib/screens/master_detail.dart",
        content: [
          "import 'package:flutter/material.dart';",
          "",
          "class Item {",
          "  const Item({required this.id, required this.title, required this.body});",
          "  final int id;",
          "  final String title;",
          "  final String body;",
          "}",
          "",
          "const _items = <Item>[",
          "  Item(id: 1, title: 'First', body: 'Body of the first item.'),",
          "  Item(id: 2, title: 'Second', body: 'Body of the second item.'),",
          "  Item(id: 3, title: 'Third', body: 'Body of the third item.'),",
          "];",
          "",
          "class MasterScreen extends StatelessWidget {",
          "  const MasterScreen({super.key});",
          "",
          "  @override",
          "  Widget build(BuildContext context) {",
          "    return Scaffold(",
          "      appBar: AppBar(title: const Text('Items')),",
          "      body: ListView.builder(",
          "        itemCount: _items.length,",
          "        itemBuilder: (ctx, i) {",
          "          final item = _items[i];",
          "          return ListTile(",
          "            title: Text(item.title),",
          "            onTap: () => Navigator.of(ctx).push(",
          "                  MaterialPageRoute(builder: (_) => DetailScreen(item: item)),",
          "                ),",
          "          );",
          "        },",
          "      ),",
          "    );",
          "  }",
          "}",
          "",
          "class DetailScreen extends StatelessWidget {",
          "  const DetailScreen({super.key, required this.item});",
          "  final Item item;",
          "",
          "  @override",
          "  Widget build(BuildContext context) {",
          "    return Scaffold(",
          "      appBar: AppBar(title: Text(item.title)),",
          "      body: Padding(",
          "        padding: const EdgeInsets.all(24),",
          "        child: Text(item.body, style: Theme.of(context).textTheme.bodyLarge),",
          "      ),",
          "    );",
          "  }",
          "}",
          "",
        ].join("\n"),
      },
    ],
  },
  {
    id: "tpl.settings-screen",
    name: "Settings Screen",
    description: "Settings with switches, dropdowns, and section headers.",
    category: "UI",
    icon: "⚙️",
    screens: ["SettingsScreen"],
    widgets: ["SwitchListTile", "DropdownButton", "ListTile"],
    stateManagement: "setState",
    routing: "none",
    estimatedComplexity: "simple",
    generatesDart: true,
    files: [
      {
        path: "lib/screens/settings_screen.dart",
        content: [
          "import 'package:flutter/material.dart';",
          "",
          "class SettingsScreen extends StatefulWidget {",
          "  const SettingsScreen({super.key});",
          "",
          "  @override",
          "  State<SettingsScreen> createState() => _SettingsScreenState();",
          "}",
          "",
          "class _SettingsScreenState extends State<SettingsScreen> {",
          "  bool _darkMode = false;",
          "  bool _notifications = true;",
          "  String _language = 'English';",
          "",
          "  @override",
          "  Widget build(BuildContext context) {",
          "    return Scaffold(",
          "      appBar: AppBar(title: const Text('Settings')),",
          "      body: ListView(",
          "        children: [",
          "          const _SectionHeader('Appearance'),",
          "          SwitchListTile(",
          "            title: const Text('Dark mode'),",
          "            value: _darkMode,",
          "            onChanged: (v) => setState(() => _darkMode = v),",
          "          ),",
          "          const _SectionHeader('Notifications'),",
          "          SwitchListTile(",
          "            title: const Text('Push notifications'),",
          "            value: _notifications,",
          "            onChanged: (v) => setState(() => _notifications = v),",
          "          ),",
          "          const _SectionHeader('Language'),",
          "          ListTile(",
          "            title: const Text('Language'),",
          "            trailing: DropdownButton<String>(",
          "              value: _language,",
          "              items: const [",
          "                DropdownMenuItem(value: 'English', child: Text('English')),",
          "                DropdownMenuItem(value: 'Indonesia', child: Text('Indonesia')),",
          "                DropdownMenuItem(value: 'Español', child: Text('Español')),",
          "              ],",
          "              onChanged: (v) => setState(() => _language = v ?? _language),",
          "            ),",
          "          ),",
          "        ],",
          "      ),",
          "    );",
          "  }",
          "}",
          "",
          "class _SectionHeader extends StatelessWidget {",
          "  const _SectionHeader(this.title);",
          "  final String title;",
          "",
          "  @override",
          "  Widget build(BuildContext context) {",
          "    return Padding(",
          "      padding: const EdgeInsets.fromLTRB(16, 16, 16, 8),",
          "      child: Text(title, style: Theme.of(context).textTheme.titleSmall?.copyWith(color: Theme.of(context).colorScheme.primary)),",
          "    );",
          "  }",
          "}",
          "",
        ].join("\n"),
      },
    ],
  },
];

/** Get a template by id. */
export function getTemplate(id: string): FlutterTemplateWithFiles | undefined {
  return flutterTemplates.find((t) => t.id === id);
}

/** List templates (optionally filtered by category). */
export function listTemplates(category?: string): FlutterTemplateWithFiles[] {
  return category
    ? flutterTemplates.filter((t) => t.category === category)
    : flutterTemplates;
}

/** List all template categories. */
export function templateCategories(): string[] {
  return Array.from(new Set(flutterTemplates.map((t) => t.category)));
}

// Re-export the placeholder for backward compat.
export const templatesInfo = {
  name: "templates",
  description: "Flutter templates module",
};
