/** Widget Catalog */
import type { WidgetCatalogEntry, WidgetCategory } from "../types";
export const widgetCatalog: WidgetCatalogEntry[] = [
  { id: "widget.column", name: "Column", category: "layout", description: "Lays out children vertically.", properties: [{ name: "children", type: "List<Widget>", required: true, description: "Widgets below one another" }, { name: "mainAxisAlignment", type: "MainAxisAlignment", required: false, defaultValue: "start", description: "Main axis alignment" }], constructorSignature: "Column({...})", example: "Column(children: [Text('A'), Text('B')])", bestPractices: ["Use mainAxisAlignment", "Wrap in Expanded"], commonMistakes: ["Not handling overflow", "Using Column in scrollable without Expanded"], performanceNotes: ["Avoid deep nesting"], import: "package:flutter/material.dart", sdk: "flutter" },
  { id: "widget.row", name: "Row", category: "layout", description: "Lays out children horizontally.", properties: [{ name: "children", type: "List<Widget>", required: true, description: "Widgets side by side" }], constructorSignature: "Row({...})", example: "Row(children: [Icon(Icons.menu), Text('Title')])", bestPractices: ["Use Expanded for flexible children"], commonMistakes: ["Not wrapping in Expanded"], performanceNotes: ["Keep child count low"], import: "package:flutter/material.dart", sdk: "flutter" },
  { id: "widget.stack", name: "Stack", category: "layout", description: "Overlays children on top of each other.", properties: [{ name: "children", type: "List<Widget>", required: true, description: "Layered widgets" }], constructorSignature: "Stack({...})", example: "Stack(children: [Container(color: Colors.blue), Positioned(bottom: 16, child: FAB())])", bestPractices: ["Use Positioned for overlay"], commonMistakes: ["Not using Positioned"], performanceNotes: ["Avoid many layers"], import: "package:flutter/material.dart", sdk: "flutter" },
  { id: "widget.container", name: "Container", category: "layout", description: "Combines painting, positioning, and sizing.", properties: [{ name: "child", type: "Widget?", required: false, description: "Child widget" }, { name: "padding", type: "EdgeInsetsGeometry?", required: false, description: "Inner spacing" }], constructorSignature: "Container({...})", example: "Container(padding: EdgeInsets.all(16), child: Text('Hi'))", bestPractices: ["Use decoration for borders"], commonMistakes: ["Setting both color and decoration"], performanceNotes: ["Use SizedBox for sizing only"], import: "package:flutter/material.dart", sdk: "flutter" },
  { id: "widget.scaffold", name: "Scaffold", category: "material", description: "Basic Material Design visual layout structure.", properties: [{ name: "appBar", type: "PreferredSizeWidget?", required: false, description: "Top app bar" }, { name: "body", type: "Widget?", required: false, description: "Primary content" }], constructorSignature: "Scaffold({...})", example: "Scaffold(appBar: AppBar(title: Text('App')), body: Center(child: Text('Hi')))", bestPractices: ["One Scaffold per screen"], commonMistakes: ["Nesting Scaffolds"], performanceNotes: ["Cost is in children"], import: "package:flutter/material.dart", sdk: "material" },
  { id: "widget.appbar", name: "AppBar", category: "material", description: "Material Design app bar.", properties: [{ name: "title", type: "Widget?", required: false, description: "Title" }, { name: "actions", type: "List<Widget>?", required: false, description: "Trailing widgets" }], constructorSignature: "AppBar({...})", example: "AppBar(title: Text('My App'), actions: [IconButton(icon: Icon(Icons.search), onPressed: () {})])", bestPractices: ["Use actions for icons"], commonMistakes: ["Too many actions"], performanceNotes: ["Lightweight"], import: "package:flutter/material.dart", sdk: "material" },
  { id: "widget.textfield", name: "TextField", category: "input", description: "Material Design text input.", properties: [{ name: "controller", type: "TextEditingController?", required: false, description: "Controls text" }, { name: "decoration", type: "InputDecoration", required: false, description: "Label, hint" }], constructorSignature: "TextField({...})", example: "TextField(decoration: InputDecoration(labelText: 'Email'))", bestPractices: ["Dispose controllers", "Use TextFormField in forms"], commonMistakes: ["Not disposing controllers"], performanceNotes: ["Reuse controllers"], import: "package:flutter/material.dart", sdk: "material" },
  { id: "widget.listview", name: "ListView", category: "scroll", description: "Scrollable list with lazy building.", properties: [{ name: "children", type: "List<Widget>?", required: false, description: "Static items" }, { name: "itemBuilder", type: "Function?", required: false, description: "Lazy builder" }], constructorSignature: "ListView({...})", example: "ListView.builder(itemCount: 100, itemBuilder: (ctx, i) => ListTile(title: Text('Item $i')))", bestPractices: ["Use .builder for dynamic lists"], commonMistakes: ["Using children for large lists"], performanceNotes: [".builder is lazy"], import: "package:flutter/material.dart", sdk: "flutter" },
  { id: "widget.elevatedbutton", name: "ElevatedButton", category: "input", description: "Material Design elevated button.", properties: [{ name: "onPressed", type: "VoidCallback?", required: true, description: "Tap callback" }, { name: "child", type: "Widget", required: true, description: "Content" }], constructorSignature: "ElevatedButton({...})", example: "ElevatedButton(onPressed: () {}, child: Text('Submit'))", bestPractices: ["Use Text as child"], commonMistakes: ["Using RaisedButton"], performanceNotes: ["Lightweight"], import: "package:flutter/material.dart", sdk: "material" },
  { id: "widget.card", name: "Card", category: "material", description: "Material Design card with elevation.", properties: [{ name: "child", type: "Widget?", required: false, description: "Content" }, { name: "elevation", type: "double", required: false, defaultValue: "1.0", description: "Shadow depth" }], constructorSignature: "Card({...})", example: "Card(child: Padding(padding: EdgeInsets.all(16), child: Text('Content')))", bestPractices: ["Use with ListTile"], commonMistakes: ["Forgetting padding"], performanceNotes: ["Slight overhead from elevation"], import: "package:flutter/material.dart", sdk: "material" },
  { id: "widget.expanded", name: "Expanded", category: "layout", description: "Expands child to fill available space.", properties: [{ name: "child", type: "Widget", required: true, description: "Widget to expand" }, { name: "flex", type: "int", required: false, defaultValue: "1", description: "Flex factor" }], constructorSignature: "Expanded({...})", example: "Row(children: [Text('L'), Expanded(child: Text('R'))])", bestPractices: ["Use flex for proportions"], commonMistakes: ["Using outside Flex context"], performanceNotes: ["Very lightweight"], import: "package:flutter/material.dart", sdk: "flutter" },
  { id: "widget.navigationbar", name: "NavigationBar", category: "navigation", description: "Material 3 bottom navigation.", properties: [{ name: "destinations", type: "List<NavigationDestination>", required: true, description: "Tab destinations" }, { name: "selectedIndex", type: "int", required: true, description: "Current tab" }], constructorSignature: "NavigationBar({...})", example: "NavigationBar(selectedIndex: 0, destinations: [...])", bestPractices: ["Use with IndexedStack"], commonMistakes: ["Using BottomNavigationBar (deprecated)"], performanceNotes: ["Efficient"], import: "package:flutter/material.dart", sdk: "material" },
  { id: "widget.customscrollview", name: "CustomScrollView", category: "scroll", description: "ScrollView composing slivers.", properties: [{ name: "slivers", type: "List<Widget>", required: true, description: "Sliver widgets" }], constructorSignature: "CustomScrollView({...})", example: "CustomScrollView(slivers: [SliverAppBar(...), SliverList(...)])", bestPractices: ["Use with SliverAppBar"], commonMistakes: ["Non-sliver in slivers"], performanceNotes: ["Highly efficient for large content"], import: "package:flutter/material.dart", sdk: "flutter" },
];
export function getWidget(id: string): WidgetCatalogEntry | undefined { return widgetCatalog.find(w => w.id === id); }
export function searchWidgets(query: string, category?: WidgetCategory): WidgetCatalogEntry[] { const q = query.toLowerCase(); return widgetCatalog.filter(w => { if (category && w.category !== category) return false; return w.name.toLowerCase().includes(q) || w.description.toLowerCase().includes(q); }); }
export function widgetCategories(): WidgetCategory[] { return Array.from(new Set(widgetCatalog.map(w => w.category))); }
